### PR TITLE
Generator upgrade

### PR DESCRIPTION
**Pull request by JEuler**

### CODE REVIEW

**Comment by JEuler** [comment]
Oh, not so easy, built_value_generator is needed to be upgraded. Will move to the draft. :)

**Comment by JEuler** [comment]
https://github.com/google/built_value.dart/pull/1028 - Need this

**Comment by lejard-h** [comment]
also for `chopper_generator` ? or just `chopper_built_value` ?

**Comment by JEuler** [comment]
@lejard-h For generator - yeah, we need to upgrade code_builder, and it leads for few things to be updated :)

**Comment by diegotori** [comment]
@JEuler looks like google/built_value.dart#1031 has already upgraded `built_value_generator`. Hopefully this should suffice for finally releasing Chopper 4.0.0 with full Null-safety, correct?

**Comment by JEuler** [comment]
@diegotori Probably. :) Upgraded the libs.

**Pull request merged**
