### PR TITLE
Preserve uri current query params in buildUri

### LINKED ISSUE #165: Uri building doesn't preserve query parameters
In request when `buildUri` is called in [Line 165](https://github.com/lejard-h/chopper/blob/develop/chopper/lib/src/request.dart#L165) only query parameters provided with `@Query` annotation are included in the URL and the immediate ones existing in `url` are replaced with those. They should be merged instead.

### PR DESCRIPTION
**Pull request by momt99**
Fixes #165

### CODE REVIEW

**Comment by JEuler** [comment]
@stewemetal What do you think? :)

**Comment by stewemetal** [comment]
LGTM!
Thanks @momt99 for the contribution!

**Review by stewemetal — APPROVED** [review]

**Comment by stewemetal** [comment]
The failing Travis check's cause is the following:

```console
TASK: dartanalyzer
Analyzing example...
  error • Target of URI hasn't been generated: 'angular_example.template.dart'. • lib/angular_example.dart:6:8 • uri_has_not_been_generated
  error • Target of URI hasn't been generated: 'main.template.dart'. • web/main.dart:8:8 • uri_has_not_been_generated
2 errors found.
The command "./tool/travis.sh build dartanalyzer dartfmt" exited with 3.
```

**Comment by JEuler** [comment]
@stewemetal We should (and will) fix the tests but this thing is looking cool. Merging! :)

**Comment by JEuler** [comment]
Or maybe I'm too quick and this should go in this PR :'(

**Pull request merged**
