### PR TITLE
:sparkles: Attach request/response to interceptor log lines

### PR DESCRIPTION
**Pull request by Maxr1998**
As discussed in #470.

### CODE REVIEW

**Comment by Maxr1998** [comment]
(gonna fix the build failure in a minute, forgot to add some imports)

**Comment by techouse** [comment]
LGTM

@Guldem & @JEuler any remarks?

**Review by techouse — APPROVED** [review]

**Review by JEuler — APPROVED** [review]
LGTM

**Review by JEuler — APPROVED** [review]

**Comment by Maxr1998** [comment]
Thank you!

**Comment by Guldem** [comment]
> Thank you!

Thanks for adding the log records.

**Comment by techouse** [comment]
I'll make a release with this feature later today or tomorrow.

**Comment by JEuler** [comment]
@techouse @Maxr1998 Thank you so much!

**Pull request merged**
