### PR TITLE
:arrow_up: Bump Dart SDK constraint to ">=2.17.0 <4.0.0"

### PR DESCRIPTION
**Pull request by techouse**
With the recent release of [Flutter 3.10.0](https://github.com/flutter/flutter/releases/tag/3.10.0) also comes the migration to Dart 3.0.

Since the package is currently limited to

```yaml
sdk: ">=2.17.0 <3.0.0"
```

I thought it would be wise to follow suit with other prominent Flutter packages and bump it up to
```yaml
sdk: ">=2.17.0 <4.0.0"
```

I've also regenerated some `*.g.dart` files in the process and bumped the versions of all the packages.

### CODE REVIEW

**Review by JEuler — APPROVED** [review]

**Comment by JEuler** [comment]
Hoooray!

**Comment by techouse** [comment]
@JEuler all the versions I put down here are the versions of the master branch + 0.0.1. Is that ok?

**Comment by techouse** [comment]
@JEuler can you please release this once you have time?

**Comment by JEuler** [comment]
Sure, I'm planning to do it today!

**Pull request merged**
