### PR TITLE
Make code quality improvements in generator.dart

### PR DESCRIPTION
**Pull request by stewemetal**
I found myself browsing though the implementation of the generator to study how it works (great job @lejard-h btw!) and I made some code quality improvements along the way. I _really_ hope that I didn't break anything. Following up on this thought, I will look into writing tests for the generator. :]

### CODE REVIEW

**Comment by JEuler** [comment]
LOL, same time, @lejard-h :) Well played :)

**Comment by lejard-h** [comment]
What are you planning on to test the generator ? 
Besides unit test on some functions, maybe we should have golden files to test generated outputs

**Comment by lejard-h** [comment]
Also we should take a look at how to prepare chopper for new Null Safety types :)

**Comment by JEuler** [comment]
@lejard-h Should we do that in a new branch (talking about Null Safety)? Or we will continue that branch? What about merging this PR? :)

**Comment by stewemetal** [comment]
> What are you planning on to test the generator ?
> Besides unit test on some functions, maybe we should have golden files to test generated outputs

I would actually create annotated service classes (like when using the library for real) and expected "generated" classes which we can compare the output to.

This is just a plan for now, I'm not really deep into code generator testing for the time being.

**Comment by stewemetal** [comment]
Also, we should definitely prepare for nullable types! :)

**Pull request merged**
