### PR TITLE
Packages upgraded

### PR DESCRIPTION
**Pull request by JEuler**

### CODE REVIEW

**Comment by JEuler** [comment]
@stewemetal @lejard-h guys? :)

**Comment by JEuler** [comment]
@stewemetal Yeah, I have run all tests I saw. All green. 

We can setup some kind of CI for this project. https://medium.com/flutter/test-flutter-apps-on-travis-3fd5142ecd8c Like Travis.

**Comment by JEuler** [comment]
Okay, thx. :) Let's see what we can do next :)

**Comment by lejard-h** [comment]
Test are already running on Travis :) 
https://travis-ci.org/github/lejard-h/chopper

**Comment by lejard-h** [comment]
I will publish the package as soon as possible or I will give you uploader right :)

**Pull request merged**
