### PR TITLE
:bookmark: release 6.1.2 (2nd attempt)

### PR DESCRIPTION
**Pull request by techouse**
The 2nd attempt of https://github.com/lejard-h/chopper/pull/418

# 6.1.2

* [FIX] https://github.com/lejard-h/chopper/pull/419
* [CHORE] https://github.com/lejard-h/chopper/pull/417

### CODE REVIEW

**Comment by techouse** [comment]
@JEuler how to fix this dirty commit log?

**Comment by JEuler** [comment]
Probably we just need to kind of git reset the master branch to the develop branch, or something like that.

**Review by JEuler — APPROVED** [review]

**Comment by JEuler** [comment]
The same problem, hm

**Comment by JEuler** [comment]
https://github.com/lejard-h/chopper/actions/runs/4970537171/jobs/8894473866

**Comment by techouse** [comment]
Oh god, I made a typo 🙈

Instead of
```bash
echo '${{ secrets.PUB_CREDENTIALS }}' > "$XDG_CONFIG_HOME/dart/pub-credentials.json"
```

it should be

```bash
echo '${{ secrets.CREDENTIAL_JSON }}' > "$XDG_CONFIG_HOME/dart/pub-credentials.json"
```

**Pull request merged**
