### PR TITLE
:sparkles: implement Dart 3 class modifiers

### PR DESCRIPTION
**Pull request by techouse**
- bump minimum Dart SDK version to 3.0.0
- bump dependencies to the latest (except `analyzer`)
- implement [Dart 3 class modifiers](https://dart.dev/language/class-modifiers)
- bump all package major versions:
  - chopper: 7.0.0
  - chopper_generator: 7.0.0
  - chopper_built_value: 2.0.0

### CODE REVIEW

**Comment by techouse** [comment]
@JEuler I have added [class modifiers](https://dart.dev/language/class-modifiers) to make class inheritance more strict where I thought it necessary. Let me know your thoughts.

**Comment by JEuler** [comment]
What do you think about sdk: ">=3.0.0 <4.0.0"? That is a big thing as I understand. Personally I don't have problems with that already, but maybe for someone that will be a problem. 

Any way, we should make it major then. :)

**Comment by techouse** [comment]
> What do you think about sdk: ">=3.0.0 <4.0.0"?

Class modifiers are a Dart 3 thing. Dart 2 doesn't support them.

> Any way, we should make it major then. :)

Yep.

- chopper: 7.0.0
- chopper_generator: 7.0.0
- chopper_built_value: 2.0.0

**Comment by JEuler** [comment]
Yeah, I know about the Dart 2-3. That's cool then, thank you!

**Review by JEuler — APPROVED** [review]

**Pull request merged**
