### PR TITLE
:bookmark: release v8.0.0

### PR DESCRIPTION
**Pull request by techouse**
# chopper

## 8.0.0

- #604
- **BREAKING CHANGE**:
  - #547
    - `RequestInterceptor` and Function `RequestInterceptor`s are removed 
    - `ResponseInterceptor` and Function `ResponseInterceptor`s are removed
    - See [Migrating to 8.0.0](https://docs.google.com/document/d/e/2PACX-1vQFoUDisnSJBzzXCMaf53ffUD1Bvpu-1GZ_stzfaaCa0Xd3WKIegbd1mmavEQcMT6r6v8z02UqloKuC/pub) for more information and examples
  - #610

# chopper_generator

## 8.0.0

- #604
- **BREAKING CHANGE**:
  - #547
    - `RequestInterceptor` and Function `RequestInterceptor`s are removed 
    - `ResponseInterceptor` and Function `ResponseInterceptor`s are removed
    - See [Migrating to 8.0.0](https://docs.google.com/document/d/e/2PACX-1vQFoUDisnSJBzzXCMaf53ffUD1Bvpu-1GZ_stzfaaCa0Xd3WKIegbd1mmavEQcMT6r6v8z02UqloKuC/pub) for more information and examples

## 3.0.0

- Require Chopper ^8.0.0

### CODE REVIEW

**Comment by techouse** [comment]
@Guldem I have written a short migration guide https://docs.google.com/document/d/1GkxktMbNi8VM5YzJwFuA19KMWeY96jrGmMsq867P28Y/edit?usp=sharing

Would you mind checking it out and adding more info, notes and/or examples?

CC / @JEuler

**Comment by Guldem** [comment]
> @Guldem I have written a short migration guide around the `Interceptor`s https://docs.google.com/document/d/1GkxktMbNi8VM5YzJwFuA19KMWeY96jrGmMsq867P28Y/edit?usp=sharing and plan to attach it to the changelog.
> 
> Would you mind checking it out and adding more info, notes and/or examples?
> 
> The publish dry run fails for the same reasons as in #606
> 
> CC / @JEuler

I will check next Tuesday and add stuff if necessary 😄

**Comment by techouse** [comment]
> I will check next Tuesday and add stuff if necessary 😄

Thanx man! Much appreciated!

The link from the comment

> https://docs.google.com/document/d/1GkxktMbNi8VM5YzJwFuA19KMWeY96jrGmMsq867P28Y/edit?usp=sharing

is to a an editable version. The link in the changelog and PR description is an immutable copy of that or maybe even a PDF, whatever is easier I guess.

**Comment by Guldem** [comment]
> > I will check next Tuesday and add stuff if necessary 😄
> 
> Thanx man! Much appreciated!
> 
> The link from the comment
> 
> > https://docs.google.com/document/d/1GkxktMbNi8VM5YzJwFuA19KMWeY96jrGmMsq867P28Y/edit?usp=sharing
> 
> is to a an editable version. The link in the changelog and PR description is an immutable copy of that same document.

I added some feedback and updated the examples. Why not just have a markdown file in the repository with the migration plan instead of a google docs?

**Comment by techouse** [comment]
Why? I've seen this in a few other repos. So I thought why not do the same. 🤷‍♂️

**Review by Guldem — APPROVED** [review]
LGTM!

**Comment by techouse** [comment]
> LGTM!

Thanx for the feedback and awesome PR #547 ♥️

**Review by JEuler — APPROVED** [review]
Great job guys! Thank you so much for being active!

**Comment by Guldem** [comment]
> > LGTM!
> 
> Thanx for the feedback and awesome PR #547 ♥️

> Great job guys! Thank you so much for being active!

@techouse @JEuler Thanks for feedback and support!

**Pull request merged**
