### PR TITLE
Provide an example using an Isolate Worker Pool with Squadron

### PR DESCRIPTION
**Pull request by techouse**
This is a follow-up on https://github.com/lejard-h/chopper/issues/158#issuecomment-1245991530

Since wiring all this up isn't really that straightforward, I decided to write an example using:

- [json_serializable](https://github.com/google/json_serializable.dart)
- [squadron](https://github.com/d-markey/squadron)
- [squadron_builder](https://github.com/d-markey/squadron_builder)

Essentially all one needs to do is:

1. install the dependencies: `dart pub add squadron squadron_builder`
2. make a service like `example/lib/json_decode_service.dart`
3. run code generation: `dart run build_runner build`
4. wire up `example/lib/json_decode_service.dart` with a custom `JsonConverter`
5. configure and start a `WorkerPool`
6. run HTTP requests like a boss using Isolate Workers 😎

### CODE REVIEW

**Comment by JEuler** [comment]
Maybe we can add the info somewhere in our documentation? :) 
https://github.com/lejard-h/chopper/blob/develop/faq.md - like here?

**Comment by techouse** [comment]
Aha. Didn't realise that section existed. 😅 Will rather update the markdowns than adding these files.

**Comment by JEuler** [comment]
It is cool to add an example anyway, but we need to point to it in Readme. :)

**Comment by techouse** [comment]
Ok. Will add the info into the readme.

**Comment by JEuler** [comment]
Thank you very much!

**Comment by techouse** [comment]
@JEuler done.

**Comment by JEuler** [comment]
This is so much cool, wow! 🐶 Thank you so much!

**Review by JEuler — APPROVED** [review]

**Comment by techouse** [comment]
@JEuler I just checked and the Github pages dox didn't get updated with this content. What needs to be done in order to publish it?

**Pull request merged**
