### PR TITLE
Null safety stable

### PR DESCRIPTION
**Pull request by lejard-h**
Great job all !
- @fryette 
- @Vovanella95 
- @JEuler
- @stewemetal

### CODE REVIEW

**Comment by diegotori** [comment]
Congrats on finally reaching stable for null-safety. @JEuler do you know when this will actually get released to pub.dev? Thanks in advance.

**Comment by JEuler** [comment]
@diegotori This question is for bossman @lejard-h :D

**Comment by diegotori** [comment]
@lejard-h please let us know when this new version goes live. Some of us are itching to finally convert our chopper classes into null-safety. Thanks in advance.

**Comment by lejard-h** [comment]
@diegotori 4.0.0 published :)

I hope next time will be faster, I configured github actions to auto publish packages when push on master

**Pull request merged**
