### PR TITLE
:bookmark: release v7.1.0

### PR DESCRIPTION
**Pull request by techouse**
# chopper

## 7.1.0

- #545
- #543
- #548

# chopper_generator

## 7.1.0

- #545
- #549

### CODE REVIEW

**Comment by techouse** [comment]
@JEuler @Guldem due to the new library requirements of `chopper_generator` this the run order here will have to be as follows:

1. merge to master -> release job triggers
2. release job releases `chopper` v7.1.0
3. release job might fail or succeed in releasing `chopper_generator` because it requires `chopper` v7.1.0 which has been released moments before
4. in case the release in step 3 fails, re-run 3

**Review by Guldem — APPROVED** [review]
Makes sense 👌

**Comment by JEuler** [comment]
Sure, cool! Thank you sooo much! 🍺

**Comment by techouse** [comment]
> Sure, cool! Thank you sooo much! 🍺

I still need approval for this though 👯

**Review by JEuler — APPROVED** [review]

**Pull request merged**
