### PR TITLE
Add @FiledMap @PartMap @PartFileMap

### PR DESCRIPTION
**Pull request by meysam1717**
I try to add @FiledMap @PartMap @PartFileMap to chopper library.
Also add generator codes and test them.

### CODE REVIEW

**Review by JEuler — APPROVED** [review]

**Comment by JEuler** [comment]
Hm, looks cool.

**Comment by JEuler** [comment]
Thank you very much! 👍

**Comment by JEuler** [comment]
Could you please fix the format? :)

**Comment by JEuler** [comment]
Please have a look - still errors in some files. :(

**Comment by meysam1717** [comment]
Can i run this test on local?  If yes how can and could you send me related urls?

**Comment by JEuler** [comment]
>Also add generator codes and test them
Do you mean you have tested it? Or do you have plans to add tests?

**Comment by meysam1717** [comment]
I test it in production.
I am new flutter developer and i work on my first project in flutter for this reason i don't know about test but if needed i try to write tests.

**Review by JEuler — APPROVED** [review]

**Comment by JEuler** [comment]
Okay, as it adds new code, it would be cool to add tests for the new code! Thank you for the contribution.

**Pull request merged**
