### PR TITLE
update Changelog for 4.0.0 release

### PR DESCRIPTION
**Pull request by lejard-h**

### CODE REVIEW

**Comment by lejard-h** [comment]
@all-contributors please add @lejard-h
@all-contributors please add @stewemetal for code, review, tests and documentations
@all-contributors please add @JEuler for code, review, tests and documentations
@all-contributors please add @fryette for code
@all-contributors please add @Vovanella95 for code

**Comment by lejard-h** [comment]
@all-contributors please add @lejard-h
@all-contributors please add @stewemetal for code, review, test and doc
@all-contributors please add @JEuler for code, review, test and doc
@all-contributors please add @fryette for code
@all-contributors please add @Vovanella95 for code

**Comment by lejard-h** [comment]
@all-contributors please add @lejard-h for code, review, test and doc
@all-contributors please add @stewemetal for code, review, test and doc
@all-contributors please add @JEuler for code, review, test and doc
@all-contributors please add @fryette for code
@all-contributors please add @Vovanella95 for code

**Comment by lejard-h** [comment]
@all-contributors please add @lejard-h for code, review, test and doc

**Comment by lejard-h** [comment]
@all-contributors please add @stewemetal for code, review, test and doc

**Comment by lejard-h** [comment]
@all-contributors please add @JEuler for code, review, test and doc

**Comment by lejard-h** [comment]
@all-contributors please add @fryette for code

**Comment by lejard-h** [comment]
@all-contributors please add @Vovanella95 for code

**Comment by lejard-h** [comment]
@JEuler it just does not seem to work :/ I will add that later

**Comment by lejard-h** [comment]
My bad It created other PR :D

**Comment by lejard-h** [comment]
@all-contributors please add @Vovanella95 for code

**Comment by JEuler** [comment]
Cool thing!

**Review by JEuler — APPROVED** [review]

**Review by stewemetal — APPROVED** [review]
Cool 👍

**Pull request merged**
