### PR TITLE
Analyzer upgrade

### PR DESCRIPTION
**Pull request by JEuler**

### CODE REVIEW

**Comment by stewemetal** [comment]
The PR itself is OK of course, but the analyzer build step is failing 😕

**Comment by JEuler** [comment]
Yeah, we need to rework actions. Let's go in this PR.

**Comment by stewemetal** [comment]
@JEuler CI is green, we're ready to deploy 💪

**Review by stewemetal — APPROVED** [review]

**Comment by JEuler** [comment]
Awesome job! Thank you! One question:
expect(converted is Response<String>, isTrue); - why such checks are removed? :)

**Comment by stewemetal** [comment]
> Awesome job! Thank you! One question: expect(converted is Response, isTrue); - why such checks are removed? :)

Because - as the Analyzer correctly pointed it out -, since `converted` is always a `Response`, the check does not provide any added value to the test. 

`jsonConverter.convertResponse<K, SV>(res)` is type safe, at least in a way that it always returns a `Response`.

**Comment by JEuler** [comment]
Cooool!

**Pull request merged**
