### PR TITLE
The Big Public API Documentation Update, volume 4.

### PR DESCRIPTION
**Pull request by stewemetal**
I've added some more docs updates which were pending on my local branches. This is still a WIP, I'll add docs and the example for the Authenticator too.

### CODE REVIEW

**Review by JEuler — APPROVED** [review]
Cool "Sending file(s)" thing!

**Comment by JEuler** [comment]
Do you need any help with that? :)

**Comment by stewemetal** [comment]
Thanks for asking!

I had to take some time away from open source lately (changing jobs, university work, etc.), but things are stabilizing now. I'll get beck to this in 2 weeks if it can wait. 

I'll gladly continue the doc updates. 😄

**Comment by MoralCode** [comment]
Would it be possible to add something to the socumentation to explain how the contents of [this](https://github.com/lejard-h/chopper/commit/4cc602494e45ea997ae5a7f903492f2fa664482a ) commit were generated?

**Comment by fryette** [comment]
@stewemetal still don't need help?)

**Comment by stewemetal** [comment]
> @stewemetal still don't need help?)

Yeah, feel free to continue what I started. 😉 Unfortunately, life was too dense in the last few months. 😞

**Comment by techouse** [comment]
What's the status of this now @stewemetal  @JEuler @fryette?

The lib is at v6 at the moment, so I assume a massive overhaul is due to this PR.

**Comment by JEuler** [comment]
I cannot answer for @stewemetal but I think we need a new PR for doc update

**Comment by stewemetal** [comment]
Hey folks,
Sorry for not getting back to this PR for so long. Actually, I've opted out of Flutter dev and I'm focusing my full effort on native Android dev.

Feel free to close this PR and/or use it to back future doc updates.

**Comment by JEuler** [comment]
@stewemetal Do you have any blogs or etc? I would love to read why you have moved to native dev :) Is that because of automotive? :)

**Comment by stewemetal** [comment]
So this is the place for ads 😄

I do have a personal site which I'm planning to make posts on, but for now only my Android (and some Flutter) talks are on it in an organized fashion:

[https://istvanjuhos.dev
](https://istvanjuhos.dev)

The thing is, I was a native Android dev way before Flutter became a thing. 😅

I taught Flutter at university here in Budapest for 2.5 years (created the curriculum for the course as well with [@danim1130](https://github.com/danim1130)). Things didn't play out for me as I planned with Flutter, so I had to cut corners.

**Comment by JEuler** [comment]
Understood! Added you in LI. :) I have the same fate, but Flutter worked for me (at the moment). I have Android native experience :) 

Thanks for sharing, cool blog!

**Comment by techouse** [comment]
> [https://istvanjuhos.dev ](https://istvanjuhos.dev)

Oh, cool! 😎 I come from web and am currently loving Flutter.

**Comment by stewemetal** [comment]
Thanks for the kind words!

@JEuler I saw you have quite some articles on Medium, nice history! 🤩 

@techouse I guess it was an easier transition, as Flutter is closer to web dev than mobile dev IMHO (Dart is still closer to JS/TS than Java/Kotlin or Swift from my perspective, and declarative UI comes from the web as well).

**Comment by JEuler** [comment]
Thank you! I like to write and to share knowledge in some way. :)

**Comment by techouse** [comment]
I'm closing this one as it's severely out of date.

**Pull request closed without merging**
